### ISSUE TITLE
Timeout per string

### ISSUE THREAD

**Issue by Vrv18** [AIcrowd/learning-to-smell-starter-kit#2]
Regarding this: Prediction i.e. def predict has timeout of 1 second per smile string.

Does it mean that if any one string exceeds the time limit, the submissions will fail? Or is it cumulative?

**Comment by skbly7** [comment]
Yes, the submission as a whole will fail upon timeout.

**Comment by Vrv18** [comment]
I think we should clarify that 😅 

What is the cumulative timestamps on which it fails?
